version: '3.3'

services:
  traefik:
    container_name: "chefbook-traefik"
    image: "traefik:v2.5.3"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--certificatesresolvers.primary.acme.httpchallenge=true"
      - "--certificatesresolvers.primary.acme.httpchallenge.entrypoint=websecure"
      - "--certificatesresolvers.primary.acme.email=support@chefbook.space"
      - "--certificatesresolvers.primary.acme.storage=/letsencrypt/acme.json"
    volumes:
        - ./data/letsencrypt:/letsencrypt
        - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      chefbook-web:
  postgres:
    container_name: chefbook-postgres
    image: postgres:14.0-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:?err}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?err}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./data/postgres/schema/initdb:/docker-entrypoint-initdb.d
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      chefbook-web:
  backend:
    container_name: chefbook-backend
    build: backend
    depends_on:
      - postgres
    ports:
      - "${BACKEND_PORT?-5000}:5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry.rule=Host(`api.${HTTP_HOST}`)"
      - "traefik.http.routers.registry.entrypoints=websecure"
      - "traefik.http.routers.registry.tls.certresolver=primary"
    environment:
      - APP_ENV=${APP_ENV:-debug}
      - GIN_MODE=${APP_ENV:-debug}
      - HTTP_HOST=api.${HTTP_HOST:-localhost}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_KEY_FILE_NAME=${FIREBASE_KEY_FILE_NAME}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY:?err}
      - SALT_COST=${SALT_COST:-10}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:?err}
      - S3_SECRET_KEY=${S3_SECRET_KEY:?err}
      - SMTP_EMAIL=${SMTP_EMAIL:?err}
      - SMTP_PASSWORD=${SMTP_PASSWORD:?err}
      - WAIT_HOSTS=postgres:5432
    networks:
      chefbook-web:
  frontend:
    container_name: chefbook-frontend
    image: nginx:1.15.7-alpine
    restart: always
    depends_on:
      - traefik
    volumes:
      - ./frontend:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${HTTP_HOST}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=primary"
    networks:
      chefbook-web:

networks:
  chefbook-web: