version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "DB_NAME"
      POSTGRES_USER: "DB_USER"
      POSTGRES_PASSWORD: "DB_PASSWORD"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .schema:/docker-entrypoint-initdb.d
      - .db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U DB_USER -d DB_NAME" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 'SERVER_CPUS'
          memory: SERVER_MEMORY_SIZE