port: "8000"

db:
  username: "postgres"
  host: "localhost"
  port: "5436"
  dbname: "postgres"
  sslmode: "disable"
auth:
  accessTokenTTL: 15m
  refreshTokenTTL: 43200m #30 days
smtp:
  host: "smtp.mail.ru"
  port: "465"