http:
  port: "8000"
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

postgres:
  host: "host.docker.internal"
  sslmode: "disable"

auth:
  accessTokenTTL: 30m
  refreshTokenTTL: 720h #30 days

smtp:
  host: "smtp.mail.ru"
  port: "465"

mail:
  templates:
    emailVerification: "./templates/email_verification.html"
  subjects:
    emailVerification: "ChefBook Account Activation"